server:
  port: 8080
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: user
            uri: lb://user
            predicates:
              - path=/user/**
          - id: vehicle
            uri: lb://vehicle
            predicates:
              - path=/vehicle/**